### ISSUE TITLE
elm-watch hangs on error

### ISSUE THREAD

**Issue by peacememories** [lydell/elm-watch#92] opened 2024-03-01 11:20 UTC
Whenever some command like `elm-watch make` fails (see #91 ), the command does not exit with an error, but instead requires the user to press `Ctrl+C` to exit. This is fine in interactive terminals, but when calling the builder with e.g. `subprocess.check_call` for automation, this hangs the calling process. It would be nice to either check whether the current shell is interactive or allow overriding this behavior with a flag

**Comment by lydell** [comment] 2024-03-01 12:16
Hi! How do I reproduce this?

**Comment by peacememories** [comment] 2024-03-04 08:58
Interestingly I can't reproduce it outside of our project.

The code that gets triggered is this:

https://github.com/lydell/elm-watch/blob/f6f6bd670b52aa21852f4a12308c434ca126fc60/src/index.ts#L133

The way I produce the error I'm getting is the following:

- Install elm and elm-watch: `npm i elm elm-watch`
- Create a new elm project with `npx elm init`
- Create a default elm-watch config with `npx elm-watch init`
- Create a very simple `src/Main.elm`, e.g. containing `main = "test"`
- Run `ELM_HOME=<a directory you cannot write to> npx elm-watch make`

This results in a permission denied error and then crashes with `thread blocked indefinitely in an MVar operation`.

What I don't get:

All environments (even calling it from `subprocess.run` in python, which is annoying) have `process.stdout.isTTY` set to true. But the "Exiting elm-watch" message is only displayed in our project.

I'll try to isolate the issue some more, it feels like something is getting stuck, specifically in our environment.

**Comment by lydell** [comment] 2024-04-02 06:21
I’m closing this for now. Feel free to post more info when you find it and we’ll reopen!

**Comment by lydell** [comment] 2024-04-02 06:25
I’m closing this for now. Feel free to post more info when you find it and we’ll reopen!

**Comment by lydell** [comment] 2024-04-12 07:17
Looks like it only happens when you have `preprocess` set in elm-watch.json.

**Closed** 2024-04-12 08:02 UTC

**Comment by lydell** [comment] 2024-04-12 08:10
Fix released in v1.1.3.

**Comment by peacememories** [comment] 2024-04-12 09:01
Hey, thanks for keeping up with this even when I wasn't very responsive. I kinda got pulled to other topics after I failed to reproduce this properly
